//
// Created by Will Dixon on 2021-05-17.
//

#ifndef MINIMAL_SDK_FREQ_PERIOD_CONVERTER_P_H
#define MINIMAL_SDK_FREQ_PERIOD_CONVERTER_P_H

#define NANO 1000000000

#include <stdint.h>

#endif //MINIMAL_SDK_FREQ_PERIOD_CONVERTER_P_H
