COMPRESSION_TYPES = {'NONE': 1, "ZSTD": 3, "LZ4": 4, "LZ4HC": 5}
COMPRESSION_LEVELS = {'NONE': [0], "ZSTD": list(range(1, 23)), "LZ4": [0], "LZ4HC": list(range(10))}

TIME_TYPES = {'TIME_ARRAY_INT64_NS': 1, 'GAP_ARRAY_INT64_INDEX_DURATION_NS': 2, 'GAP_ARRAY_INT64_INDEX_NUM_SAMPLES': 3,
              'START_TIME_NUM_SAMPLES': 4}
VALUE_TYPES = {'INT64': 1, 'DOUBLE': 2, 'DELTA_INT64': 3, 'XOR_DOUBLE': 4}
