OVERWRITE_SETTING_NAME = 'overwrite'
PROTECTED_MODE_SETTING_NAME = 'protected_mode'

ALLOWABLE_OVERWRITE_SETTINGS = ['error', 'ignore', 'overwrite']
ALLOWABLE_PROTECTED_MODE_SETTINGS = ['True', 'False']
