trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
- group: atriumdb-release

jobs: 
  - job: run_build_dev
    displayName: Run build dev
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
    - bash: |
        sudo apt-get update && sudo apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64
        pip install build
      displayName: Setup build environment

    - bash: |
        cd tsc-lib
        cmake -Bcmake-build-release -DCMAKE_TOOLCHAIN_FILE=windows-TC-mingw.cmake -DCMAKE_BUILD_TYPE='Release';
        cmake --build cmake-build-release --target Block;
        mkdir ../sdk/bin
        cp cmake-build-release/src/Block/libTSC.dll ../sdk/bin/libTSC.dll;
        rm -rf cmake-build-release/**;
        cmake -Bcmake-build-release -H. -DCMAKE_BUILD_TYPE='Release';
        cmake --build cmake-build-release --target Block;
        cp cmake-build-release/src/Block/libTSC.so ../sdk/bin/libTSC.so;
        cd ..
      displayName: Build C libraries

    - bash: |
        cd sdk
        python -m build
      displayName: Build SDK package
