trigger:
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
- group: atriumdb-release
- name: build_date
  value: format('{0:yyyyMMdd}',pipeline.startTime)


jobs: 
  - job: run_build_dev
    displayName: Run build dev
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
    - bash: |
        pip install cibuildwheel==4.2.1
        pip install twine
      displayName: Setup build environment

    - bash: |
        cd sdk
        python -m cibuildwheel --platform linux --output-dir dist
      displayName: Build SDK package

    - bash: |
        VERSION=$(grep -Po '^version = "\K[^"]*' sdk/pyproject.toml)
        DATE=$(date '+%Y%m%d')
        COMMIT=$(Build.SourceVersion)
        cd sdk/dist
        for wheel in atriumdb-${VERSION}-*.whl; do
          mv "$wheel" "${wheel/-py3-none-/-${DATE}_${COMMIT}-py3-none-}"
        done

    - task: TwineAuthenticate@1
      inputs:
        artifactFeed: 'Physiological Data System/adb-py-internal'
    - bash: |
          python -m twine upload --skip-existing -r adb-py-internal --config-file $(PYPIRC_PATH) sdk/dist/*.whl
      displayName: Upload build artifacts