trigger: none

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
- group: atriumdb-release

jobs: 
  - job: run_build_dev
    displayName: Run build dev
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
    - bash: |
        pip install cibuildwheel==4.2.1
      displayName: Setup build environment

    - bash: |
        cd sdk
        python -m cibuildwheel --platform linux --output-dir dist
      displayName: Build SDK package
