
trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

variables:
- group: atriumdb-release

steps:
- bash: |
     git push --prune https://$(GITHUB_PAT)@github.com/LaussenLabs/adb-lib-sdk/ +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
  # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')