name: atriumdb_SDK_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
 - manual

pool:
  vmImage: ubuntu-20.04

variables:
- group: atriumdb-release

stages:
- stage: Build
  jobs:
    - job: run_build_release
      displayName: Run build release

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'

      - bash: |
          sudo apt-get update && sudo apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64
          pip install build
          pip install twine
        displayName: Setup build environment

      - bash: |
          cd tsc-lib
          cmake -Bcmake-build-release -DCMAKE_TOOLCHAIN_FILE=windows-TC-mingw.cmake -DCMAKE_BUILD_TYPE='Release';
          cmake --build cmake-build-release --target Block;
          mkdir -p ../sdk/bin
          cp cmake-build-release/src/Block/libTSC.dll ../sdk/bin/libTSC.dll;
          cmake -Bcmake-build-release -H. -DCMAKE_BUILD_TYPE='Release';
          cmake --build cmake-build-release --target Block;
          cp cmake-build-release/src/Block/libTSC.so ../sdk/bin/libTSC.so;
          cd ..
        displayName: Build C libraries

      - bash: |
          cd sdk
          python -m build
        displayName: Build SDK package

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: 'Physiological Data System/atriumdb-py-internal'
        
      - bash: |
            python -m twine upload -r atriumdb-py-internal --config-file $(PYPIRC_PATH) sdk/dist/*.whl
            python -m twine upload --verbose --repository-url https://test.pypi.org/legacy/ -p $(test_pypi_token) -u __token__ sdk/dist/*.whl
        displayName: Upload build artifacts
      
      

