name: atriumdb_SDK_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
 - manual

pool:
  vmImage: ubuntu-20.04

stages:
- stage: Build
  jobs:
    - job: run_build_release_c
      displayName: Run build release C

      steps:
      - bash: |
          sudo apt-get update && apt-get install -y tzdata cmake build-essential gdb libzstd-dev liblz4-dev python3.10 mingw-w64
          sed -i -e 's/\r$//' tsc-lib/build_release.sh
          chmod 755 tsc-lib/build_release.sh
          ./build_release.sh

    - job: run_build_release_sdk
      displayName: Run build release sdk

      steps:
      - bash: |
          pip install build
          pip install twine
          cd sdk
          python -m build

