name: atriumdb_SDK_Release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
- group: atriumdb-release

parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string
  - name: pypiReleaseFeed
    displayName: PyPI Release Feed
    default: atriumdb-test-pypi
    values:
      - atriumdb-test-pypi
      - atriumdb-release-pypi
    type: string
    

stages:
- stage: Build
  jobs:
    - job: run_build_release
      displayName: Run build release

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.12'

      - bash: |
          pip install build
          pip install cibuildwheel==4.2.1
          pip install twine
        displayName: Setup build environment

      - bash: |
          cd sdk
          python -m cibuildwheel --platform linux --output-dir dist
          python -m build --sdist
        displayName: Build SDK package

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: 'Physiological Data System/adb-py-internal'
          pythonUploadServiceConnection: ${{ parameters.pypiReleaseFeed }}
        
      - bash: |
            python -m twine upload --skip-existing -r adb-py-internal --config-file $(PYPIRC_PATH) sdk/dist/*.whl
        displayName: Upload build artifacts
        
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'github.com_bgreer101'
          repositoryName: 'LaussenLabs/atriumdb'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'userSpecifiedTag'
          tag: '${{ parameters.releaseVersion }}'
          releaseNotesSource: 'inline'
          releaseNotesInline: ''
          assets: |
            sdk/dist/*.whl
            sdk/dist/*.gz
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'
      

